CREATE DATABASE authdb;

CREATE USER uloyalty WITH PASSWORD 'dede23dgwu2376fytsw';
CREATE USER uauth WITH PASSWORD '2gSgu136txww*66WaAq';
CREATE USER uorder WITH PASSWORD 'YYwsg!!0)OpswaaQaz';


GRANT ALL PRIVILEGES ON DATABASE loyaltydb TO uloyalty;
GRANT ALL PRIVILEGES ON DATABASE authdb TO uauth;
GRANT ALL PRIVILEGES ON DATABASE orderdb TO uorder;


\connect loyaltydb
GRANT ALL PRIVILEGES ON SCHEMA public TO uloyalty;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO uloyalty;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO uloyalty;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON FUNCTIONS TO uloyalty;

\connect authdb
GRANT ALL PRIVILEGES ON SCHEMA public TO uauth;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO uauth;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO uauth;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON FUNCTIONS TO uauth;

\connect orderdb
GRANT ALL PRIVILEGES ON SCHEMA public TO uorder;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO uorder;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO uorder;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON FUNCTIONS TO uorder;
