// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecases/order/scenarios/scenarios.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	dto "github.com/Axel791/order/internal/usecases/order/dto"
	gomock "github.com/golang/mock/gomock"
)

// MockCreateOrderUseCase is a mock of CreateOrderUseCase interface.
type MockCreateOrderUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockCreateOrderUseCaseMockRecorder
}

// MockCreateOrderUseCaseMockRecorder is the mock recorder for MockCreateOrderUseCase.
type MockCreateOrderUseCaseMockRecorder struct {
	mock *MockCreateOrderUseCase
}

// NewMockCreateOrderUseCase creates a new mock instance.
func NewMockCreateOrderUseCase(ctrl *gomock.Controller) *MockCreateOrderUseCase {
	mock := &MockCreateOrderUseCase{ctrl: ctrl}
	mock.recorder = &MockCreateOrderUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateOrderUseCase) EXPECT() *MockCreateOrderUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockCreateOrderUseCase) Execute(ctx context.Context, order dto.CreateOrder) (dto.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, order)
	ret0, _ := ret[0].(dto.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockCreateOrderUseCaseMockRecorder) Execute(ctx, order interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockCreateOrderUseCase)(nil).Execute), ctx, order)
}
