// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.0
// source: loyalty_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LoyaltyService_CreateLoyaltyBalance_FullMethodName = "/loyalty.LoyaltyService/CreateLoyaltyBalance"
	LoyaltyService_ConcludeUserBalance_FullMethodName  = "/loyalty.LoyaltyService/ConcludeUserBalance"
)

// LoyaltyServiceClient is the client API for LoyaltyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LoyaltyServiceClient interface {
	CreateLoyaltyBalance(ctx context.Context, in *CreateLoyaltyBalanceRequest, opts ...grpc.CallOption) (*CreateLoyaltyBalanceResponse, error)
	ConcludeUserBalance(ctx context.Context, in *ConcludeUserBalanceRequest, opts ...grpc.CallOption) (*ConcludeUserBalanceResponse, error)
}

type loyaltyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLoyaltyServiceClient(cc grpc.ClientConnInterface) LoyaltyServiceClient {
	return &loyaltyServiceClient{cc}
}

func (c *loyaltyServiceClient) CreateLoyaltyBalance(ctx context.Context, in *CreateLoyaltyBalanceRequest, opts ...grpc.CallOption) (*CreateLoyaltyBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLoyaltyBalanceResponse)
	err := c.cc.Invoke(ctx, LoyaltyService_CreateLoyaltyBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loyaltyServiceClient) ConcludeUserBalance(ctx context.Context, in *ConcludeUserBalanceRequest, opts ...grpc.CallOption) (*ConcludeUserBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConcludeUserBalanceResponse)
	err := c.cc.Invoke(ctx, LoyaltyService_ConcludeUserBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoyaltyServiceServer is the server API for LoyaltyService service.
// All implementations must embed UnimplementedLoyaltyServiceServer
// for forward compatibility.
type LoyaltyServiceServer interface {
	CreateLoyaltyBalance(context.Context, *CreateLoyaltyBalanceRequest) (*CreateLoyaltyBalanceResponse, error)
	ConcludeUserBalance(context.Context, *ConcludeUserBalanceRequest) (*ConcludeUserBalanceResponse, error)
	mustEmbedUnimplementedLoyaltyServiceServer()
}

// UnimplementedLoyaltyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLoyaltyServiceServer struct{}

func (UnimplementedLoyaltyServiceServer) CreateLoyaltyBalance(context.Context, *CreateLoyaltyBalanceRequest) (*CreateLoyaltyBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLoyaltyBalance not implemented")
}
func (UnimplementedLoyaltyServiceServer) ConcludeUserBalance(context.Context, *ConcludeUserBalanceRequest) (*ConcludeUserBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConcludeUserBalance not implemented")
}
func (UnimplementedLoyaltyServiceServer) mustEmbedUnimplementedLoyaltyServiceServer() {}
func (UnimplementedLoyaltyServiceServer) testEmbeddedByValue()                        {}

// UnsafeLoyaltyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoyaltyServiceServer will
// result in compilation errors.
type UnsafeLoyaltyServiceServer interface {
	mustEmbedUnimplementedLoyaltyServiceServer()
}

func RegisterLoyaltyServiceServer(s grpc.ServiceRegistrar, srv LoyaltyServiceServer) {
	// If the following call pancis, it indicates UnimplementedLoyaltyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LoyaltyService_ServiceDesc, srv)
}

func _LoyaltyService_CreateLoyaltyBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLoyaltyBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoyaltyServiceServer).CreateLoyaltyBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoyaltyService_CreateLoyaltyBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoyaltyServiceServer).CreateLoyaltyBalance(ctx, req.(*CreateLoyaltyBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoyaltyService_ConcludeUserBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConcludeUserBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoyaltyServiceServer).ConcludeUserBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoyaltyService_ConcludeUserBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoyaltyServiceServer).ConcludeUserBalance(ctx, req.(*ConcludeUserBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LoyaltyService_ServiceDesc is the grpc.ServiceDesc for LoyaltyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LoyaltyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "loyalty.LoyaltyService",
	HandlerType: (*LoyaltyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLoyaltyBalance",
			Handler:    _LoyaltyService_CreateLoyaltyBalance_Handler,
		},
		{
			MethodName: "ConcludeUserBalance",
			Handler:    _LoyaltyService_ConcludeUserBalance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "loyalty_service.proto",
}
